server:
  port : 9099


spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: faraz
    password: Questmaster123
    driver:
      class: oracle.jdbc.driver.OracleDriver
  security:
    oauth2:
      client:
        registration:
          linkedin:
            client-id: ????
            client-secret: ????
            scope:  r_liteprofile, r_emailaddress
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: LinkedIn
            client-authentication-method: post
        provider:
          linkedin:
            authorization-uri: https://www.linkedin.com/oauth/v2/authorization
            token-uri: https://www.linkedin.com/uas/oauth2/accessToken
            user-info-uri: https://api.linkedin.com/v2/me
            jwk-set-uri:
            user-name-attribute: id